language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
r_packages:
  - DescriptiveStats.OBeu
  - devtools
  - forecast
  - foreach
  - jsonlite
  - locfit
  - purrr
  - rjson
  - rlist
  - TimeSeries.OBeu
  - trend
  - tseries
apt_packages:
  - libxml2-dev
sudo: required
warnings_are_errors: false
after_success:
- Rscript -e 'covr::codecov()'