language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel  
before_install:
  - tlmgr install index
github_packages:
  - devtools
  - TimeSeries.OBeu
r_packages:
 - DescriptiveStats.OBeu
 - forecast
 - foreach
 - jsonlite
 - locfit
 - purrr
 - rjson
 - rlist
 - trend
 - tseries
addons:
  apt:
    packages:
      - libxml2-dev
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::codecov()'